### PR TITLE
#279: Reset default terminal color in pull.sh.

### PR DESCRIPTION
**Pull request by serundeputy**

### CODE REVIEW

**Comment by pirog** [comment]
nice @serundeputy, do we want to do this in push.sh as well?

**Comment by serundeputy** [comment]
Added `DEFAULT_COLOR` to `push.sh` as well.

**Comment by pirog** [comment]
@serundeputy awesome! let's get an edit to that https://github.com/kalabox/lando/blob/master/docs/changelog/2017.md so your contribution can be immortalized in the annals of gitbook documentation

**Comment by serundeputy** [comment]
@pirog does that mean add a `beta.9` section and a bullet description for this?

**Comment by pirog** [comment]
@serundeputy yup

**Comment by serundeputy** [comment]
Updated changelog.

**Comment by pirog** [comment]
@serundeputy awesome, will merge this as soon as tests pass!

**Pull request merged**
